### ISSUE TITLE
hg38 data or instructions on generation of data resources

### ISSUE THREAD

**Issue by ameynert** [eugenegardner/indelible#1]
Could the developers provide a hg38 data zip file or instructions on how to generate a custom data folder. If the latter, I will generate for hg38 myself and share.

**Comment by eugenegardner** [comment]
Hello,

I am working on getting an Hg38 data package together and will let you know when it has been pushed live.

**Comment by eugenegardner** [comment]
Hello,

I have generated a hg38 dataset as a

**Comment by eugenegardner** [comment]
Hello,

I have generated a pull request (#2) for code/data which should get Hg38 working with InDelible. I have:

1. Added a hg38 data zip into the ./data/ folder. This _does not_ include the reference genome itself, or the wmasker.obinary file necessary for the blast step.
2. Modified the README to (hopefully) provide good instructions on getting InDelible to work with Hg38.
* This now includes a section in "Output" about how to perform recommended default filtering as we have done in DDD
3. Modified the code base to be more adaptable to non-hg19 references.
4. Made `--config` a required option for ALL InDelible commands, which helps to ease the transition to Hg38.
5. Tested InDelible on both an Hg19 and Hg38 Decipher Developmental Disorders .cram file, which generated expected output (single de novo variant deletion within _MECP2_).

Please let me know if you are successful in getting InDelible to run with your data. Make sure to perform a new `git checkout` of InDelible and switch to the "hg38" branch.

**Comment by ameynert** [comment]
It's working fine, thank you for the detailed instructions @eugenegardner. I've written a Nextflow pipeline to run the steps as vr-runner was not immediately installable on the system I'm using. Currently the nextflow.config file is set to use PBSpro and has one hard-coded path, also the R scripts for filtering assume Rscript is at /usr/bin/Rscript, so it's not 100% portable yet. https://github.com/ameynert/nf-indelible
