### ISSUE TITLE
Version of the required Python packages

### ISSUE THREAD

**Issue by greekkey** [eugenegardner/indelible#10]
Hi. I would like to report some incompatible issues on the versions of the required Python packages. 
1. The file "requirements.txt" only restricted the versions of numpy v1.7.2 and scikit-learn v0.21.3. When executing the command "pip install -r requirements.txt", the latest version of the other packages will be installed. However, the latest version of pandas (v1.3.4, @ Nov.18, 2021) requires numpy >=1.17.3, conflicting with the assigned numpy version. 
2.  Then I assigned all the packages to the validated version and could solve the conflict. But pysam v0.15.3 has another error (ERROR: Command errored out with exit status 1) in my system (I'm using Python 3.8.5). Then I installed the latest version of pysam (v0.18.0) without an error. 
3. Summary of the packages I used.
	cython		v0.29.13
	numpy		v1.17.2
	pandas		v0.25.1
	pyfaidx	v0.5.5.2
	pysam		v0.18.0
	scipy		v1.3.1
	scikit-learn	v0.21.3
	PyYAML		v5.1.2
	Biopython	v1.74
	intervaltree	v3.0.2

I report this issue and suggest assigning version of packages (at least for pandas).

**Comment by eugenegardner** [comment]
Thanks for the suggestions and I agree that it is probably better to provide fixed version numbers for required packages. This was not an issue until some major changes to numpy that resulted in strange errors while building InDelible.

I have pushed a new version of InDelible live that directly assigns version numbers to required packages.

**Comment by eugenegardner** [comment]
Closing this as I believe it is resolved. Just an FYI but PyMAL was bumped to v5.4 due to a warning about potential security flaws (#11). 

Please reopen if you have any other issues.
