### ISSUE TITLE
singularity data files permission issue

### ISSUE THREAD

**Issue by igibmukeshkumar** [eugenegardner/indelible#15]
Hi Sir/Madam,

It's a wonderful pipeline for the SV analysis. I pulled the .sif file for Indelible using command  _**singularity pull docker://mercury/indelible**_ and used indelible in singularity as **_singularity shell --bind /path /path/to/indelible_latest.sif_**

I have few queries regarding Indelible tool as follows;
1.  There are permission issues due to which in related command showing error that file has **Read only permission** for the following set of files;
Path: 
**No read and execute permission ( -rwx------)**
/usr/src/app/indelible/data/DDG2P_18VI2019.bed
/usr/src/app/indelible/data/GRCh38_full_analysis_set.fa
/usr/src/app/indelible/data/cleaned_exac_with_pLI_march16_anno.txt   
/usr/src/app/indelible/data/hgnc_gene_synonyms.txt
/usr/src/app/indelible/data/hgnc_genes.tsv
/usr/src/app/indelible/data/hs37d5.fa

2. In GitHub documentation there is not mentioned about **_'-p' option in database command_** . The guidelines contains the following statement;
_The database command generates the allele frequency and breakpoint database required for the next step – [Annotate](https://github.com/HurlesGroupSanger/indelible#5-annotate). If analysing a small amount of data, it is highly recommended to use the **'-p' flag** with this command to include breakpoints from the initial DDD study described in our [manuscript](https://github.com/HurlesGroupSanger/indelible#how-to-cite-indelible)._

Please look into the issues and elaborate little more about **'-p' flag.**

Thank you 
Regards
Mukesh

**Comment by eugenegardner** [comment]
Hello Mukesh,

Apologies for the delay in responding – I recently switched emails and didn't receive a notification...

1. Is there a specific issue with having these files be read only? it is a bit of an effort to modify the singularity instance, so would need a good justification to go back and change anything.

2. Apologies – this is a typo. It should say the **'--priors'** flag. I have updated the README on the github page.

Best,

Eugene

**Comment by igibmukeshkumar** [comment]
Hello Eugene,

**_Please see the bold font line showing error to access file while running command._**

_(base) [mukesh.kumar@hn1 tools]$_ srun -p compute -N 2 --cpus-per-task=40 -J JID singularity exec --bind /lustre/binukumar/wes_data/BAMs_38/ --pwd /usr/src/app/indelible/ /lustre/binukumar/tools/indelible_latest.sif indelible.py complete --i /lustre/binukumar/wes_data/BAMs_38/GDN6859_hg38.bam --o /lustre/binukumar/wes_data/BAMs_38 --r /usr/src/app/indelible/data/GRCh38_full_analysis_set.fa --config /usr/src/app/indelible/config.hg38.yml
22/06/22 - 11:57:41: Fetching reads...
Total number of split reads processed: 6315716
22/06/22 - 12:03:43: Aggregating across positions...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyfaidx/__init__.py", line 358, in __init__
    self.file = self._fasta_opener(filename, 'r+b'
**PermissionError: [Errno 13] Permission denied: '/usr/src/app/indelible/data/GRCh38_full_analysis_set.fa'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/indelible/indelible.py", line 208, in <module>
    indelible.aggregate_positions(reads_path, args.input_path, counts_path, args.reference_path, config)
  File "/usr/src/app/indelible/indelible/aggregate_positions.py", line 126, in aggregate_positions
    reference = Fasta(reference_path, as_raw=True)
  File "/usr/local/lib/python3.8/dist-packages/pyfaidx/__init__.py", line 981, in __init__
    self.faidx = Faidx(
  File "/usr/local/lib/python3.8/dist-packages/pyfaidx/__init__.py", line 367, in __init__
    raise FastaNotFoundError(
pyfaidx.FastaNotFoundError: Cannot read FASTA file /usr/src/app/indelible/data/GRCh38_full_analysis_set.fa
srun: error: node6: task 0: Exited with exit code 1
22/06/22 - 11:57:41: Fetching reads...
Total number of split reads processed: 6315716
22/06/22 - 12:03:52: Aggregating across positions...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyfaidx/__init__.py", line 358, in __init__
    self.file = self._fasta_opener(filename, 'r+b'
**PermissionError: [Errno 13] Permission denied: '/usr/src/app/indelible/data/GRCh38_full_analysis_set.fa'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/indelible/indelible.py", line 208, in <module>
    indelible.aggregate_positions(reads_path, args.input_path, counts_path, args.reference_path, config)
  File "/usr/src/app/indelible/indelible/aggregate_positions.py", line 126, in aggregate_positions
    reference = Fasta(reference_path, as_raw=True)
  File "/usr/local/lib/python3.8/dist-packages/pyfaidx/__init__.py", line 981, in __init__
    self.faidx = Faidx(
  File "/usr/local/lib/python3.8/dist-packages/pyfaidx/__init__.py", line 367, in __init__
    raise FastaNotFoundError(
**pyfaidx.FastaNotFoundError: Cannot read FASTA file /usr/src/app/indelible/data/GRCh38_full_analysis_set.fa**
srun: error: node7: task 1: Exited with exit code 1


Thanks 
Mukesh

**Comment by igibmukeshkumar** [comment]
>
