### ISSUE TITLE
version tags

### ISSUE THREAD

**Issue by marrip** [eugenegardner/indelible#3]
Hi, I got a recommendation from a colleague and wanted to test indelible on my data. I was wondering if it was possible to add version tags to the repo or how you are handling your releases. Thank you! 😄

**Comment by eugenegardner** [comment]
We are still _technically_ in pre-release and I hadn't yet worked out that exact issue yet – I realize now I should have done a v1.0.0 release when the preprint hit........ 

I will generate a v1.0.0 release soon to make sure it is easier to track. 

Thanks for pointing this out!

**Comment by marrip** [comment]
Hey,

fastest reply ever! Cheers for that! I will use the commit tag for now and change it to the version tag as soon as you had time to add it. Keep up the good work!

**Comment by eugenegardner** [comment]
Okay, hopefully this should be resolved now – in terms of providing release numbers. Will continue to crush the bug in #4 if necessary...
